# Generated by Django 3.0.7 on 2020-06-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
    ]
