# Generated by Django 3.0.7 on 2020-06-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0003_auto_20200611_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
