# Generated by Django 3.0.7 on 2020-06-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0004_auto_20200611_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_married',
            field=models.BooleanField(default=False),
        ),
    ]
